travis:
  secure:
    BINSTAR_TOKEN: jbdqfqjRCWKn9E5XU7f0ILApVOtDke59uSvkHkLMfeWTKPA/s/tf62o2oFN4knJOmKQXA1HzuVdKDIg3eIpyz/LdnR4ZQnUHw61G+yfJtI/SrubfsCzZr7omodiJUWBpB/TFF8AVpZRz29f8ZlF2SgeBYcvsSHnbtHJWvrWWCjXMRaN2Vb4lQsBuoRSFI6g+8wQwLJYadrsOOY+UU9z2LWmLuV4GGBgSsyj6Oz3e1m8UBmg8EZ5pHdscye0HOUv2yBX+s+jPyzswkmO9LezlTE3eZQyaXNxpPtX3nHrTDve+JLuCFJ/4KdD/nhaKt51hOC+9fb8ElO9xw+tHkGd+37ixFrYPXezw7CnNZTMAgCQI6xbFdS6WBuMiTaomqdz2ZeXyczJCS3Zcr5QefN/u6CcuIEfQY0p5P4YGm6o0ZfmM/bfLwl7fkw+VcVbRKHCfztjvVt1tzmDYD3x6z1mlXEl7tAd6u/3c5zMNYEkaB+ggONTewbHkBWHGjOpIVEXlNAVkpINH+hMvqEJUUvoIDmEmXW/dKjqh4On8U3TUCtkrNFViS3BSuIC9rBJMtQVJE4CKLHyx57L/SyDkWOtgo3CYDY5Cm8xsGjr1tlfR2UHeIB+frqC+0U9JelAizbAS5MA//SojDOqLst4BlTT7BVu+Ae6T4bb9XC78snEfFNI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
