travis:
  secure:
    BINSTAR_TOKEN: S2jpg5UUYTwZThQ/G2w3g+MnM8w6hofjvzzWTtls9s3lPIyG3NG+EmbTMoJYBK2YyYVAZBk8Eot3L5DjLP9Xl4k8B+zwZUs8gvUnDek/ZI+M1DFuspOnZmPFvw9qf+jhCsB8aZsvhxfj+ZmgFTvt0ULJ71EsRb+x0wQUhLuxfgKIKOLR+7MedB8KZ5mb4/J/XNCjzw80xFfpcIrivDA+sZXPacRTGw3TxmVPH6cnlMSxlhbxcJ5j32ykcJfRozhPSZkxgK94qZ/CwwO2mE5tmLcoPw08QRT/x5VWx7aZWxi8xo7PSIRa5oFmd3H3L52TL+iOxZic2Zzg5kmABZ8I3ftvX9yIcLruAE8Po2Spebd4L6CMsH7P2zPIxALSCzyqvQC0nSlPo27mBqLgh32fzJaDPZm0ipceD46euaPROgAF5s6U2SFd22UmhMlKWTa2ubkbMZlUQCn35XVVYQGdySRCQgCH/H8PjSaRFex8YT+b/3xlEJvMjOUzOI5lDBJzn+hxvBZpJtQOflveyfeKGbUvN9uWhBC82UNznJhCZbLjWLOWGJgDJmujzfPFlR7Vs/LSnVIbseIGyrUrhtXyKvOvOF6urfX9m6d0p9EQgHJ5Ye+dbE6bVMBP0GzmQCb0A5bVajl0NT1XxwAuD++uJS60RBmdqVtvv7fzb7y809s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
