travis:
  secure:
    BINSTAR_TOKEN: foqyMgwvOtXsKRJVsa84kinHvDtr6K3x+RxEzBaZXuSqbWBPWUXLPFrm3AU/sum1jTHRBM5z6dwxiMNiuHx5hywfCrJl5Wxe1FxHFoOFDquaIv/rlJ3zeJAiRfwOpquZJWLapHxFVrtEJOPU4C2npYm/9szN1T1mWOG6KjVACMk6AdAhYSieYBoMVSTBUAKZbYA+cPMZs7xCpC+yulqYxmjWkqmU8oPCND1zA2GZ/V5xtarpj/br6kypu9/64/yLLTG/5deOk4tJqfbI34rfOECGrQ55RyvpUfoJhWEcPWuJJVqCru6GG0cqi7jq1/J3EcheCZp2gIj+qnnHzHQzcqawBe08Z6WzC6+fyNF/tx+D7nMPIJ0CzyCD9nxCz37ugRWzx2SECZ9LEgENIKZfdomQVblR8GBLwDJ3JM+x46I8XjtAze+oMb46GtQ+N82bJjxVB8xnzsPRgefiGCNkL4wOaet6arZnBTBC12pKOqh5QG/AErgAcQE6ML+SvvpDtUtVAUNrt/A53uo9Len+pMlR4ydkyDEqpJcvAj//GGQSYltOskErb4AgZLZ7k3K4LvW033tcBn/Tjo0lV8QLdVqTWHtXVTDGeMX1+xHaW/KYUZMD1mMT386d98f58P8QZlx9ic1cqsqHKvefgVk6QpJWtps9zEP6oJwmZCkt8ks=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
