travis:
  secure:
    BINSTAR_TOKEN: EO0//buCsEGhLJHCyfeITrF1CJDpvtrK6lBMgU7IBFwTPWMzKslifh+3XJDn8pBwSZkqznTEeR04ZrW9DiEMJFoikKAXJqn3MnhvSXy71rH/TbcG2TTb+zTOBuw0irH1kCmh/W8/sHJi6W6vnexbQ0AXzVW9zLfRRk/pVG+e/DqbstZ+fYX51MK/aLeDlicDCpnCZvpv5rW0GqFWcydPNmoPmU+X8IivTI/2kx+fvrLu2+s0iOvwsdsX8drpPE6ORPHL4hwqD04GNePl69chcIaDOJLQxUBinCmalk3Z3kVAq7fiBaTLMAgQ2sGkAlAAkB5sKZUZcZRbZAhQLxWy+H/MhD/3nCWpjNhNxsJdFhkP4Nwc/rKS1f2/6s5/nRaMBQlw8ZQ+wrck7jls/VJdG3veyIx0vprV5DJzM9VhXj6kXiN1ZbGlH50XrOIbU0/p4ipPHqT5IZlHbXbUE2KRrLDcf5kb8d1z7NE1j22sKARjgliHK5xUpXKRbIzEwZDIANAJ77fDoWpeIdTb00R/Bnk81r4d29DfhgnykM1U4drEtEj+htQN1w9IroYjjJS6s2gWV9CcJ82KcVJcI9X0GHBqB5GUl9y/T8cZLAX8DSXXmCMkXWmoL43FQg/pfQzqULr9li0gm5ssHzfe1XP88JrngyrF2DO3QmVPoxYxon4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
