travis:
  secure:
    BINSTAR_TOKEN: lSc4TMSkgBcdTo56eJsIKHn8Oz+p4I+F+le3vtu34R3MoIK6zXuxiO3yjKo9HQnn82ypLWEvsKTC3NLKqmbptze4IDk16PecgDKos6MjW3nDo38Bav1juYHZ10wDlWXGF15pHr39+AGo/quSBaqyQqa98quUWrByLZ6WN+cWP3AOvaS96HvZiOj0zpWqhZsfiFgszGLHiDnf9jScs7amRuLbATW7uJx3JsNIz4pgsKW7BKZcqSk+fMWhhLQB6opJ0yPYdn1mEnSH6O3PpsboJKLe9j2khlp0E+zOqi3tMxhS06z0T6/Vk5mGIx4A1uY+2z/kZOHAUjQIE1/cq5iqmxw3yCtvoYIKuP3S7WXdJkYrRV2NGLkSHNMPle8V/7vBCdxPeWB2sEbmCLp9j8E+2LgnpjaJceL6nBhfN/vkHxoScPpxc3Re6DyqGA4Kx5OpKencuUwACr71qlVjjqkzAmh8LXsyZ8Ctd+BPJmp0pd89zd5SqlUjdahXQrkX0hjAiAmofxf+eOvVMQhEfYB47XzQOyeMr87W7P9l5W6u5cUtK6Mfsh/Tby8ujdqwFVjq0xlh4cBMlFKs2RkJo/xbKnfWmYUXqWBY1K0b+soeZupScrPMdBv1b+0g/eeoAS1mBvnfZkj7ff3/GF9fIIhtptXTnLQCI2h6A55nngEKt5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
